name: Java CI with Maven

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Java 21 using Adoptium
    - name: Set up Java 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adoptium'  # Corrected distribution

    # Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Install dependencies and run tests
    - name: Build and test with Maven
      run: mvn clean install
